// AgripeWebUI-Mobile/app/(auth)/login.tsx
import { useState } from 'react';
import {
  View,
  Text,
  TextInput,
  TouchableOpacity,
  ScrollView,
  ActivityIndicator,
  Alert,
  KeyboardAvoidingView,
  Platform,
} from 'react-native';
import { useRouter } from 'expo-router';
import { jwtDecode } from 'jwt-decode';
import { Ionicons } from '@expo/vector-icons';
import * as WebBrowser from 'expo-web-browser';
import { authService } from '../../services/authService';
import { useAuthStore } from '../../stores/authStore';
import { Colors } from '../../constants/colors';
import { GOOGLE_CLIENT_ID } from '../../constants/api';

interface JwtPayload {
  id: string;
  name?: string;
  email?: string;
}

function buildGoogleOAuthUrl(redirectUri: string): string {
  const params = new URLSearchParams({
    client_id: GOOGLE_CLIENT_ID,
    redirect_uri: redirectUri,
    response_type: 'code',
    scope: 'email profile openid',
    access_type: 'offline',
    prompt: 'select_account',
  });
  return `https://accounts.google.com/o/oauth2/v2/auth?${params.toString()}`;
}

export default function LoginScreen() {
  const router = useRouter();
  const { setAuth } = useAuthStore();
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [showPassword, setShowPassword] = useState(false);
  const [loading, setLoading] = useState(false);
  const [googleLoading, setGoogleLoading] = useState(false);

  const googleEnabled = Boolean(GOOGLE_CLIENT_ID);

  const handleLogin = async () => {
    if (!email.trim() || !password.trim()) {
      Alert.alert('Erro', 'Preencha o e-mail e a senha');
      return;
    }
    try {
      setLoading(true);
      const { token } = await authService.login({ email: email.trim(), password });
      const decoded = jwtDecode<JwtPayload>(token);
      await setAuth(token, parseInt(decoded.id), decoded.name ?? decoded.email ?? 'Usuário');
      router.replace('/(app)/home');
    } catch (error: any) {
      const status = error?.response?.status;
      if (status === 403) {
        Alert.alert('Acesso Bloqueado', 'Contate o suporte técnico.');
      } else if (status === 429) {
        Alert.alert('Muitas tentativas', 'Tente novamente em alguns minutos.');
      } else {
        Alert.alert('Erro de autenticação', 'E-mail ou senha inválidos. Verifique seus dados.');
      }
    } finally {
      setLoading(false);
    }
  };

  const handleGoogleLogin = async () => {
    if (!googleEnabled) return;
    setGoogleLoading(true);
    try {
      const redirectUri =
        Platform.OS === 'web' && typeof window !== 'undefined'
          ? `${window.location.origin}/login/callback`
          : 'agripeweb://callback';

      const oauthUrl = buildGoogleOAuthUrl(redirectUri);

      if (Platform.OS === 'web') {
        // On web: navigate directly (Google redirects back with ?code=...)
        window.location.href = oauthUrl;
      } else {
        // On native: open in-app browser and intercept deep link
        await WebBrowser.openAuthSessionAsync(oauthUrl, 'agripeweb://callback');
      }
    } catch {
      Alert.alert('Erro', 'Falha ao iniciar login com Google');
      setGoogleLoading(false);
    }
  };

  return (
    <KeyboardAvoidingView
      style={{ flex: 1, backgroundColor: Colors.background }}
      behavior={Platform.OS === 'ios' ? 'padding' : undefined}
    >
      <ScrollView
        contentContainerStyle={{
          flexGrow: 1,
          justifyContent: 'center',
          alignItems: 'center',
          padding: 24,
        }}
        keyboardShouldPersistTaps="handled"
      >
        {/* Header / Logo */}
        <View style={{ alignItems: 'center', marginBottom: 40 }}>
          <View
            style={{
              width: 80,
              height: 80,
              borderRadius: 40,
              backgroundColor: Colors.card,
              justifyContent: 'center',
              alignItems: 'center',
              borderWidth: 2,
              borderColor: Colors.success,
              marginBottom: 16,
            }}
          >
            <Ionicons name="leaf" size={40} color={Colors.success} />
          </View>
          <Text style={{ color: Colors.textPrimary, fontSize: 28, fontWeight: 'bold' }}>
            AgripeWeb
          </Text>
          <Text style={{ color: Colors.textSecondary, fontSize: 14, marginTop: 4 }}>
            Monitoramento Agrícola Inteligente
          </Text>
        </View>

        {/* Card */}
        <View
          style={{
            width: '100%',
            maxWidth: 420,
            backgroundColor: Colors.card,
            borderRadius: 16,
            padding: 28,
            borderWidth: 1,
            borderColor: Colors.cardBorder,
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 4 },
            shadowOpacity: 0.3,
            shadowRadius: 12,
            elevation: 8,
          }}
        >
          <Text
            style={{
              color: Colors.textPrimary,
              fontSize: 22,
              fontWeight: '700',
              marginBottom: 24,
              textAlign: 'center',
            }}
          >
            Entrar
          </Text>

          {/* Email field */}
          <Text style={{ color: Colors.textSecondary, fontSize: 13, marginBottom: 6 }}>
            E-mail
          </Text>
          <View
            style={{
              flexDirection: 'row',
              alignItems: 'center',
              backgroundColor: Colors.background,
              borderRadius: 10,
              borderWidth: 1,
              borderColor: Colors.cardBorder,
              marginBottom: 16,
              paddingHorizontal: 14,
            }}
          >
            <Ionicons name="mail-outline" size={18} color={Colors.textSecondary} />
            <TextInput
              style={{
                flex: 1,
                color: Colors.textPrimary,
                paddingVertical: 13,
                paddingLeft: 10,
                fontSize: 15,
              }}
              placeholder="seu@email.com"
              placeholderTextColor={Colors.textSecondary}
              value={email}
              onChangeText={setEmail}
              keyboardType="email-address"
              autoCapitalize="none"
              autoComplete="email"
              returnKeyType="next"
            />
          </View>

          {/* Password field */}
          <Text style={{ color: Colors.textSecondary, fontSize: 13, marginBottom: 6 }}>
            Senha
          </Text>
          <View
            style={{
              flexDirection: 'row',
              alignItems: 'center',
              backgroundColor: Colors.background,
              borderRadius: 10,
              borderWidth: 1,
              borderColor: Colors.cardBorder,
              marginBottom: 24,
              paddingHorizontal: 14,
            }}
          >
            <Ionicons name="lock-closed-outline" size={18} color={Colors.textSecondary} />
            <TextInput
              style={{
                flex: 1,
                color: Colors.textPrimary,
                paddingVertical: 13,
                paddingLeft: 10,
                fontSize: 15,
              }}
              placeholder="••••••••"
              placeholderTextColor={Colors.textSecondary}
              value={password}
              onChangeText={setPassword}
              secureTextEntry={!showPassword}
              autoComplete="password"
              returnKeyType="done"
              onSubmitEditing={handleLogin}
            />
            <TouchableOpacity onPress={() => setShowPassword(!showPassword)} style={{ padding: 4 }}>
              <Ionicons
                name={showPassword ? 'eye-off-outline' : 'eye-outline'}
                size={20}
                color={Colors.textSecondary}
              />
            </TouchableOpacity>
          </View>

          {/* Login button */}
          <TouchableOpacity
            onPress={handleLogin}
            disabled={loading || googleLoading}
            style={{
              backgroundColor: Colors.primary,
              borderRadius: 10,
              paddingVertical: 14,
              alignItems: 'center',
              opacity: loading || googleLoading ? 0.7 : 1,
            }}
          >
            {loading ? (
              <ActivityIndicator color="#fff" />
            ) : (
              <Text style={{ color: '#fff', fontWeight: '700', fontSize: 16 }}>Entrar</Text>
            )}
          </TouchableOpacity>

          {/* Google OAuth divider + button */}
          {googleEnabled && (
            <>
              <View
                style={{
                  flexDirection: 'row',
                  alignItems: 'center',
                  marginVertical: 20,
                }}
              >
                <View style={{ flex: 1, height: 1, backgroundColor: Colors.cardBorder }} />
                <Text
                  style={{
                    color: Colors.textSecondary,
                    fontSize: 12,
                    marginHorizontal: 12,
                  }}
                >
                  ou continue com
                </Text>
                <View style={{ flex: 1, height: 1, backgroundColor: Colors.cardBorder }} />
              </View>

              <TouchableOpacity
                onPress={handleGoogleLogin}
                disabled={loading || googleLoading}
                style={{
                  flexDirection: 'row',
                  alignItems: 'center',
                  justifyContent: 'center',
                  backgroundColor: '#fff',
                  borderRadius: 10,
                  paddingVertical: 13,
                  borderWidth: 1,
                  borderColor: '#E2E8F0',
                  opacity: loading || googleLoading ? 0.7 : 1,
                }}
              >
                {googleLoading ? (
                  <ActivityIndicator color={Colors.primary} />
                ) : (
                  <>
                    {/* Google "G" icon using text */}
                    <View
                      style={{
                        width: 22,
                        height: 22,
                        borderRadius: 11,
                        backgroundColor: '#4285F4',
                        justifyContent: 'center',
                        alignItems: 'center',
                        marginRight: 10,
                      }}
                    >
                      <Text style={{ color: '#fff', fontWeight: 'bold', fontSize: 13 }}>G</Text>
                    </View>
                    <Text
                      style={{ color: '#374151', fontWeight: '600', fontSize: 15 }}
                    >
                      Entrar com Google
                    </Text>
                  </>
                )}
              </TouchableOpacity>
            </>
          )}
        </View>

        {/* Footer */}
        <Text
          style={{
            color: Colors.textSecondary,
            fontSize: 12,
            marginTop: 24,
            textAlign: 'center',
          }}
        >
          © 2025 AgripeWeb — Sistema de Monitoramento Agrícola
        </Text>
      </ScrollView>
    </KeyboardAvoidingView>
  );
}

// AgripeWebUI/src/app/components/login/login.component.ts
import { Component } from '@angular/core';
import { Router } from '@angular/router';
import { ApiService } from '../../services/api.service';
import { FormsModule } from '@angular/forms';
import { jwtDecode } from 'jwt-decode';
import { environment } from '../../../environments/environment';
import { MatSnackBar } from '@angular/material/snack-bar';

interface DecodedToken {
  id: number;
  name: string;
  email: string;
  isAdmin: boolean;
}

/** Google OAuth 2.0 authorization endpoint */
const GOOGLE_AUTH_URL = 'https://accounts.google.com/o/oauth2/v2/auth';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css'],
  standalone: false
})
export class LoginComponent {
  email = '';
  password = '';

  get googleLoginEnabled(): boolean {
    return !!environment.googleClientId?.trim();
  }

  constructor(private fb: FormsModule, private apiService: ApiService, private router: Router, private snackBar: MatSnackBar) {}

  loginWithGoogle(): void {
    if (!this.googleLoginEnabled) return;
    const redirectUri = `${window.location.origin}/login/callback`;
    const params = new URLSearchParams({
      client_id: environment.googleClientId,
      redirect_uri: redirectUri,
      response_type: 'code',
      scope: 'email profile openid'
    });
    window.location.href = `${GOOGLE_AUTH_URL}?${params.toString()}`;
  }

  login() {
    this.apiService.login(this.email, this.password).subscribe({
      next: (response: any) => {
        const token = response?.token;
        if (token) {
          localStorage.setItem('token', token);

          try {
            // 3. DECODIFIQUE O TOKEN PARA EXTRAIR OS DADOS
            const decodedToken: DecodedToken = jwtDecode(token);

            // 4. PEGUE O ID E SALVE-O NO LOCALSTORAGE
            // IMPORTANTE: O nome do campo de ID pode variar!
            // Pode ser 'sub', 'userId', 'id', 'nameid', etc.
            // Verifique com seu back-end qual é o nome correto da "claim".
            const userId = decodedToken.id;
            localStorage.setItem('userId', userId.toString());
            localStorage.setItem('isAdmin', (decodedToken.isAdmin === true).toString());

            // 5. NAVEGUE PARA A HOME
            this.router.navigate(['/home']);

          } catch (error) {
            console.error("Erro ao decodificar o token:", error);
            this.snackBar.open('Token inválido ou corrompido.', 'Fechar', { duration: 4000 });
          }


          this.router.navigate(['/home']);
        } else {
          this.snackBar.open('Token inválido.', 'Fechar', { duration: 4000 });
        }
      },
      error: (err) => {
        if (err.status === 403) {
          this.snackBar.open('Contate o suporte técnico.', 'Fechar', { duration: 0 });
        } else if (err.status === 429) {
          this.snackBar.open('Muitas tentativas. Tente novamente em alguns minutos.', 'Fechar', { duration: 6000 });
        } else {
          this.snackBar.open('Usuário ou senha inválidos.', 'Fechar', { duration: 4000 });
        }
      }
    });
  }
}


<div class="login-page">
  <div class="login-panel">
    <div class="login-brand">
      <span class="brand-icon">💧</span>
      <h1 class="brand-name">AgripeWeb</h1>
      <p class="brand-subtitle">Monitoramento de Irrigação</p>
    </div>
    <form (ngSubmit)="login()" #loginForm="ngForm">
      <div class="field-group">
        <label>Email</label>
        <input type="text" name="email" [(ngModel)]="email" placeholder="seu@email.com" required />
      </div>
      <div class="field-group">
        <label>Senha</label>
        <input type="password" name="password" [(ngModel)]="password" placeholder="••••••••" required />
      </div>
      <button type="submit" class="btn-login">Entrar</button>
      <button *ngIf="googleLoginEnabled" type="button" class="google-btn" (click)="loginWithGoogle()">
        Entrar com Google
      </button>
    </form>
  </div>
</div>
